import Foundation
import SwiftData

/// Seeds the SwiftData store with realistic sample `InBodyRecord`s so that
/// screenshots generated by `fastlane snapshot` show meaningful content on a
/// fresh simulator install.
///
/// Triggered by launch argument `-UITestScreenshots 1` (injected by
/// `MyBodyUITests/SnapshotScreenshotsUITests.swift`).
enum ScreenshotSampleData {
    static var isEnabled: Bool {
        let args = ProcessInfo.processInfo.arguments
        guard let i = args.firstIndex(of: "-UITestScreenshots"), i + 1 < args.count else {
            return false
        }
        return args[i + 1] == "1" || args[i + 1].lowercased() == "yes"
    }

    @MainActor
    static func seedIfNeeded(container: ModelContainer) {
        guard isEnabled else { return }
        let context = container.mainContext
        // Clear existing records to keep screenshots deterministic.
        let descriptor = FetchDescriptor<InBodyRecord>()
        if let existing = try? context.fetch(descriptor) {
            for record in existing {
                context.delete(record)
            }
        }

        let calendar = Calendar(identifier: .gregorian)
        let now = Date()
        // A short history so the trends chart has a visible curve.
        let samples: [(daysAgo: Int, weight: Double, muscle: Double, fat: Double, fatPct: Double, bmi: Double, score: Int)] = [
            (90, 74.2, 31.8, 18.9, 25.5, 24.3, 72),
            (60, 73.1, 32.2, 17.6, 24.1, 24.0, 75),
            (30, 72.0, 32.7, 16.4, 22.8, 23.6, 78),
            (7,  71.3, 33.1, 15.5, 21.7, 23.4, 82)
        ]

        for s in samples {
            guard let date = calendar.date(byAdding: .day, value: -s.daysAgo, to: now) else { continue }
            let record = InBodyRecord(
                scanDate: date,
                scanTime: "08:30",
                weight: s.weight,
                skeletalMuscle: s.muscle,
                bodyFatMass: s.fat,
                totalBodyWater: 40.2,
                leanBodyMass: s.weight - s.fat,
                bmi: s.bmi,
                bodyFatPercent: s.fatPct,
                whr: 0.86,
                bmr: 1610,
                inbodyScore: s.score,
                visceralFatLevel: 8,
                dailyCalorie: 2380,
                segMuscleLeftArm: 3.1, segMuscleRightArm: 3.2,
                segMuscleTrunk: 26.4,
                segMuscleLeftLeg: 9.1, segMuscleRightLeg: 9.2,
                segFatLeftArm: 18.5, segFatRightArm: 18.2,
                segFatTrunk: 22.4,
                segFatLeftLeg: 20.1, segFatRightLeg: 20.0
            )
            context.insert(record)
        }
        try? context.save()
    }
}
